#!/bin/bash

# New Gaussian input header
header_content="%nprocshared=32
%mem=5000MW
%chk=TADF.chk
# td=(50-50) B3LYP/cc-pvdz scrf(solvent=Toluene)

1111

0 1
"

# Enable safe globbing when no est-n folders are found
shopt -s nullglob

# Loop over all est-n folders in the current directory
for folder in est-[0-9]*; do
    if [ ! -d "$folder" ]; then
        continue
    fi

    mol_id="${folder#est-}"

    log_file="$folder/est-${mol_id}.log"
    slurm_file="$folder/gaussiannew.sh"
    target_dir="$folder/td"
    gjf_output_file="$target_dir/est-${mol_id}-td.gjf"

    # Check whether the log file exists and contains normal Gaussian termination
    if [ -e "$log_file" ]; then
        last_lines=$(tail -n 10 "$log_file")

        if [[ "$last_lines" == *"Normal termination of Gaussian 16"* ]]; then
            echo "PM7 ground-state optimization finished normally in $folder. Preparing TD calculation."

            # Create the target td directory if it does not exist
            if [ ! -d "$target_dir" ]; then
                mkdir -p "$target_dir"
            fi

            # Copy the log file to the target directory
            cp "$log_file" "$target_dir/"
            echo "Copied $log_file to $target_dir."

            # Copy the SLURM script to the target directory
            if [ -e "$slurm_file" ]; then
                cp "$slurm_file" "$target_dir/"
                echo "Copied $slurm_file to $target_dir."
            else
                echo "Warning: $slurm_file does not exist and cannot be copied."
            fi

            # Copy log2gjf.sh to the target directory
            if [ -e "log2gjf.sh" ]; then
                cp "log2gjf.sh" "$target_dir/"
                echo "Copied log2gjf.sh to $target_dir."
            else
                echo "Warning: log2gjf.sh does not exist and cannot be copied."
            fi

            # Enter the target directory and run log2gjf.sh
            cd "$target_dir" || {
                echo "Failed to enter $target_dir."
                continue
            }

            if [ -e "log2gjf.sh" ]; then
                bash log2gjf.sh
                echo "Executed log2gjf.sh in $target_dir."
            else
                echo "Warning: log2gjf.sh was not found in $target_dir and cannot be executed."
            fi

            cd - > /dev/null

            # Process the generated .gjf file and create a new TD .gjf file
            gjf_files=("$target_dir"/*.gjf)

            if [ -e "${gjf_files[0]}" ]; then
                # Write the new header into the TD .gjf file
                echo "$header_content" > "$gjf_output_file"

                # Append molecular coordinates from the original .gjf file
                tail -n +7 "${gjf_files[0]}" >> "$gjf_output_file"

                # Remove extra blank line after charge and multiplicity
                sed -i '/0 1/{n;/^[[:space:]]*$/d}' "$gjf_output_file"

                echo "Generated TD input file: $gjf_output_file."
            else
                echo "Warning: no .gjf file was found in $target_dir."
            fi

            # Remove old .gjf and .log files generated by log2gjf.sh
            rm -f "$target_dir/est-${mol_id}.gjf"
            rm -f "$target_dir/est-${mol_id}.log"
            echo "Removed old temporary .gjf and .log files."

            # Submit the new TD job from inside the td directory
            if [ -e "$target_dir/gaussiannew.sh" ] && [ -e "$gjf_output_file" ]; then
                (
                    cd "$target_dir" || exit 1
                    sbatch "gaussiannew.sh" "est-${mol_id}-td.gjf"
                )
                echo "Submitted TD job from $target_dir: sbatch gaussiannew.sh est-${mol_id}-td.gjf"
            else
                echo "Warning: TD job was not submitted because gaussiannew.sh or the TD .gjf file is missing."
            fi

        else
            echo "Warning: calculation in $folder did not finish normally."
        fi

    else
        echo "Warning: $log_file does not exist and cannot be checked."
    fi
done