import os
import sys
from pathlib import Path
import pandas as pd
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from rdkit import RDLogger
from tqdm import tqdm


sys.path.append(str(Path(__file__).resolve().parent))
from iter_config import get_config, get_iteration, DEFAULT_DATASET_DIR

# Disable annoying RDKit warning outputs
RDLogger.DisableLog('rdApp.*')

# ==========================================
# 1. Precise path and column-name configuration
# ==========================================
ITERATION = get_iteration()
ITER_CONFIG = get_config(ITERATION)

GEN_BASE_DIR = os.environ.get("FIREFLY_GEN_BASE_DIR", ITER_CONFIG["gen_base_dir"])
DATASET_DIR = os.environ.get("FIREFLY_DATASET_DIR", DEFAULT_DATASET_DIR)

# Training set configuration
TRAIN_CSV = os.path.join(DATASET_DIR, "train.csv")
TRAIN_SMILES_COL = "TADF_SMILES"  # Explicit SMILES column name in the training set

# Generated set configuration
GENERATED_CSV = os.path.join(GEN_BASE_DIR, "novel_smiles_with_preds_and_SA_epoch049.csv")
GEN_SMILES_COL = "SMILES"         # Explicit SMILES column name in the generated set

# Result output configuration
OUTPUT_NOVEL_CSV = os.path.join(GEN_BASE_DIR, "pure_novel_scaffolds_epoch049.csv")

os.makedirs(os.path.dirname(OUTPUT_NOVEL_CSV), exist_ok=True)

# ==========================================
# 2. Core scaffold extraction function
# ==========================================
def get_scaffold(smi):
    """Safely extract the Murcko core scaffold of a molecule"""
    if not isinstance(smi, str):
        return None
    try:
        mol = Chem.MolFromSmiles(smi)
        if mol is not None:
            scaffold = MurckoScaffold.GetScaffoldForMol(mol)
            return Chem.MolToSmiles(scaffold)
    except Exception:
        pass
    return None

# ==========================================
# 3. Parse the original training set to build the known scaffold set
# ==========================================
print(f"📂 Loading the original training set: {TRAIN_CSV}")
df_train = pd.read_csv(TRAIN_CSV)

print(f"🧬 Extracting core scaffolds from the training set ({TRAIN_SMILES_COL})...")
tqdm.pandas(desc="Train Scaffolds")
df_train['Scaffold'] = df_train[TRAIN_SMILES_COL].progress_apply(get_scaffold)

# Build a set of known scaffolds for extremely fast duplicate checking
known_scaffolds = set(df_train['Scaffold'].dropna().unique())
print(f"✅ Original training set parsing completed! {len(known_scaffolds)} known old scaffolds identified.")

# ==========================================
# 4. Parse the molecules generated by the large model
# ==========================================
print(f"\n📂 Loading the Epoch49 generated set: {GENERATED_CSV}")
df_gen = pd.read_csv(GENERATED_CSV)

print(f"🧬 Extracting core scaffolds from the generated set ({GEN_SMILES_COL})...")
tqdm.pandas(desc="Generated Scaffolds")
df_gen['Scaffold'] = df_gen[GEN_SMILES_COL].progress_apply(get_scaffold)

# Remove invalid entries for which scaffolds cannot be extracted
df_gen_clean = df_gen.dropna(subset=['Scaffold']).copy()

# Identify all unique scaffolds in the generated set
generated_scaffolds = set(df_gen_clean['Scaffold'].unique())
print(f"✅ Generated set parsing completed! Epoch 49 produced {len(generated_scaffolds)} unique scaffolds.")

# ==========================================
# 5. Final scaffold comparison: identify purely novel scaffolds
# ==========================================
# Set operation: generated scaffolds minus training-set scaffolds = absolutely novel scaffolds
novel_scaffolds = generated_scaffolds - known_scaffolds

print("\n" + "🌟"*15)
print(f"📊 Final creativity report of the large model")
print(f"  - Number of old scaffolds in the training set : {len(known_scaffolds)}")
print(f"  - Total number of scaffolds in the generated set : {len(generated_scaffolds)}")
print(f"  - Number of absolutely novel scaffolds : {len(novel_scaffolds)}")
if len(generated_scaffolds) > 0:
    creativity_score = len(novel_scaffolds) / len(generated_scaffolds) * 100
else:
    creativity_score = 0.0
print(f"  - Creativity score (novel scaffold rate): {creativity_score:.2f}%")
print("🌟"*15 + "\n")

# ==========================================
# 6. Save the pure novel scaffold pool
# ==========================================
# Filter molecule rows that belong only to the purely novel scaffolds
df_pure_novel = df_gen_clean[df_gen_clean['Scaffold'].isin(novel_scaffolds)].copy()

# Remove the temporary Scaffold column to keep the data table clean
df_pure_novel = df_pure_novel.drop(columns=['Scaffold'])
df_pure_novel.to_csv(OUTPUT_NOVEL_CSV, index=False)

print(f"💾 The data table containing {len(df_pure_novel)} molecules with novel scaffold variants has been saved to: {OUTPUT_NOVEL_CSV}")