import os
import sys
import pandas as pd
from tqdm import tqdm
from rdkit import Chem
from rdkit import RDLogger
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent))
from iter_config import get_config, get_iteration


# Disable RDKit error messages
RDLogger.DisableLog('rdApp.*')

# ==========================================
# 0. Import the official RDKit SA Score calculation module
# ==========================================
from rdkit.Chem import RDConfig
sys.path.append(os.path.join(RDConfig.RDContribDir, 'SA_Score'))
import sascorer

# ==========================================
# 1. Path configuration
# ==========================================
ITERATION = get_iteration()
ITER_CONFIG = get_config(ITERATION)

GEN_BASE_DIR = os.environ.get("FIREFLY_GEN_BASE_DIR", ITER_CONFIG["gen_base_dir"])
GEN_GRAPH_DIR = os.environ.get("FIREFLY_GEN_GRAPH_DIR", os.path.join(GEN_BASE_DIR, "gen"))

# IMPORTANT:
# Property predictions are produced from graph pkl files generated by dataset_iter.py.
# dataset_iter.py now writes filtered_novel_smiles_epoch049-graph.csv, whose row order
# exactly matches the graph pkl files and therefore the prediction output.
# Do not merge predictions with the original filtered_novel_smiles_epoch049.csv.
smiles_csv_path = os.environ.get(
    "FIREFLY_GRAPH_SMILES_CSV",
    os.path.join(GEN_BASE_DIR, "filtered_novel_smiles_epoch049-graph.csv")
)

pred_csv_path = os.path.join(
    GEN_GRAPH_DIR,
    os.environ.get("FIREFLY_PREDICTION_FILENAME", "predictions_tol.csv")
)

if not os.path.exists(pred_csv_path):
    fallback_pred_csv_path = os.path.join(GEN_GRAPH_DIR, "predictions_toluene.csv")
    if os.path.exists(fallback_pred_csv_path):
        pred_csv_path = fallback_pred_csv_path

# Modification: update the output filename to indicate that it includes SA scores
output_csv_path = os.path.join(GEN_BASE_DIR, "novel_smiles_with_preds_and_SA_epoch049.csv")

os.makedirs(os.path.dirname(output_csv_path), exist_ok=True)

# ==========================================
# 2. Read data and check consistency
# ==========================================
print(f"📂 Reading graph-compatible generated molecule SMILES file: {smiles_csv_path}")
if not os.path.exists(smiles_csv_path):
    raise FileNotFoundError(
        f"Graph-compatible SMILES CSV was not found: {smiles_csv_path}\n"
        "Please run dualmol-net/dataset_iter.py first. It should generate "
        "filtered_novel_smiles_epoch049-graph.csv."
    )
df_smiles = pd.read_csv(smiles_csv_path)

print(f"📂 Reading property prediction result file: {pred_csv_path}")
df_pred = pd.read_csv(pred_csv_path)

if len(df_smiles) != len(df_pred):
    print(f"\n❌ Serious warning: row counts do not match! SMILES: {len(df_smiles)} rows, predictions: {len(df_pred)} rows.")
    print("The SMILES file must be filtered_novel_smiles_epoch049-graph.csv generated by dataset_iter.py.")
    print("The program will exit to prevent prediction-SMILES misalignment.")
    exit()
else:
    print(f"✅ Row counts perfectly match ({len(df_smiles)} rows). Starting processing...")

# ==========================================
# 3. Extract prediction columns and concatenate horizontally
# ==========================================
target_columns = [
    "Transform_absorption_nm",
    "Transform_emission_nm",
    "Transform_Delta_EST_eV",
    "Transform_PLQY_percent"
]

df_pred_selected = df_pred[target_columns]
df_merged = pd.concat([df_smiles, df_pred_selected], axis=1)

# ==========================================
# 4. Core function: industrial-grade SA Score calculation
# ==========================================
print("\n⚙️ Calculating SA Score (synthetic accessibility score) for all molecules...")

def calculate_sa_robust(smi):
    """Safely calculate the SA Score for a single molecule, preventing interruptions or missing returns."""
    # 1. Intercept non-string or NaN dirty data
    if not isinstance(smi, str):
        return None

    # 2. Try to parse and score
    try:
        mol = Chem.MolFromSmiles(smi)
        if mol is not None:
            return sascorer.calculateScore(mol)
    except Exception:
        pass # Any underlying C++ error will be intercepted

    # 3. If parsing fails or calculation errors occur, return None as a placeholder to preserve the DataFrame shape
    return None

# Enable tqdm progress bar and use pandas apply for batch calculation
tqdm.pandas(desc="Calculating SA Score")
df_merged['SA_Score'] = df_merged['SMILES'].progress_apply(calculate_sa_robust)

# ==========================================
# 5. Save the final result table
# ==========================================
df_merged.to_csv(output_csv_path, index=False)

print("\n" + "🎉" * 15)
print(f"All processing completed! A final table with {len(df_merged)} rows, including predicted properties and SA Score, has been generated.")
print(f"💾 File saved to: {output_csv_path}")
print("🎉" * 15 + "\n")
